version: "3.8"

services:
  mongodb-workshift:
    restart: unless-stopped
    image: mongo:latest
    container_name: mongodb-workshift
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGOADMIN}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGOPASS}
    networks:
      - backend
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  workshift-svc:
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    container_name: workshift-svc
    environment:
      - MONGODB_URL=${MONGOURL}
    depends_on:
      - mongodb-workshift
    networks:
      - backend
    ports:
      - "3001:3001"
    volumes:
      - .:/workshift-svc

volumes:
  mongo-data:

networks:
  backend:
    driver: bridge
